# Generated by Django 4.0.4 on 2022-05-25 05:55

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userextend_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 25, 12, 55, 56, 984288)),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='parish',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Xin vui lòng nhập đúng số điện thoại!', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
