# Generated by Django 4.0.4 on 2022-06-10 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userextend_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='activation_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='userextend',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userextend',
            name='key_expires',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='birth_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
