# Generated by Django 4.0.4 on 2022-06-23 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_alter_participant_join_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_userextend_activation_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userextend',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='userextend',
            name='key_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WorkshopHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('date', models.DateTimeField(null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workshop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.workshop')),
            ],
        ),
    ]
