# Generated by Django 4.0.4 on 2022-06-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userextend_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkshopHistory',
        ),
    ]
