# Generated by Django 4.0.4 on 2022-07-02 18:50

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_delete_workshophistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='userextend',
            options={'verbose_name': 'Người dùng(Mở rộng)', 'verbose_name_plural': 'Người dùng(Mở rộng)'},
        ),
        migrations.AlterField(
            model_name='userextend',
            name='activation_key',
            field=models.CharField(blank=True, max_length=40, verbose_name='Key kích hoạt'),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='address',
            field=models.CharField(blank=True, max_length=254, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='birth_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='Đã xác nhận Email'),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='key_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời hạn key'),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='parish',
            field=models.CharField(blank=True, max_length=100, verbose_name='Giáo xứ'),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Xin vui lòng nhập đúng số điện thoại!', regex='^\\+?1?\\d{9,15}$')], verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='ticket',
            field=models.IntegerField(default=0, verbose_name='Số vé'),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
    ]
