# Generated by Django 4.0.4 on 2022-07-10 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_alter_userextend_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userextend',
            options={'verbose_name': 'Nhập vé', 'verbose_name_plural': 'Nhập vé'},
        ),
    ]
