# Generated by Django 4.0.4 on 2022-07-10 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userextend_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextend',
            old_name='birth_date',
            new_name='birthdate',
        ),
    ]
