# Generated by Django 4.0.4 on 2022-08-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userextend_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='language',
            field=models.CharField(choices=[('vi', 'Tiếng Việt'), ('en', 'Tiếng Anh')], default='vi', max_length=10, verbose_name='Ngôn ngữ'),
        ),
    ]
