# Generated by Django 4.0.4 on 2022-09-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_userextend_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='workshop_ticket',
            field=models.IntegerField(default=0, verbose_name='Vé workshop'),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='ticket',
            field=models.IntegerField(default=0, verbose_name='Vé Thường'),
        ),
    ]
