# Generated by Django 4.0.4 on 2022-10-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_userextend_workshop_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='special_ticket',
            field=models.IntegerField(default=0, verbose_name='Vé Workshop'),
        ),
    ]
