# Generated by Django 4.0.4 on 2022-10-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20221028_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='language',
            field=models.CharField(choices=[('vi', 'Tiếng Việt'), ('en', 'Tiếng Anh (chưa hoàn thiện)')], default='vi', max_length=10, verbose_name='Ngôn ngữ'),
        ),
    ]
