# Generated by Django 4.0.4 on 2022-11-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_userextend_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='input_special_ticket',
            field=models.PositiveIntegerField(default=0, verbose_name='Nhập vé Workshop'),
        ),
    ]
