"""
Django settings for TicketApp project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from datetime import datetime, timedelta, timezone
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*&5(t+@yxqvo1pes6*+*^(s7j9wcqv1g)anqx%(@$-dg3@dt7r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'users',
    'ticket',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #Custom middleware
    'TicketApp.middlewares.RequestLoggerMiddleware',
    'TicketApp.middlewares.UserLanguageMiddleware',
]

ROOT_URLCONF = 'TicketApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TicketApp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
#Config in Local Settings
DATABASES = {
    'default': {
        'ENGINE'  : 'django.db.backends.mysql',
        'NAME'    : 'ticketapp', 
        'USER'    : '',
        'PASSWORD': '',
        'HOST'    : 'localhost',
        'PORT'    : '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/
from django.utils.translation import gettext_lazy as _

LANGUAGES = [
    ('vi', _('Tiếng Việt')),
    ('en', _('Tiếng Anh')),
]

LANGUAGE_CODE = 'vi'

LANGUAGE_COOKIE_NAME = 'language'

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

TIME_ZONE= "UTC"

USE_I18N = True

USE_TZ = True

#Date Formats
DATE_INPUT_FORMATS = ('%Y-%m-%d','%m-%d-%Y')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT= os.path.join(BASE_DIR,'static')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'staticfile'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT= os.path.join(BASE_DIR,'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Sender Config: Config in Local Settings
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER =''
EMAIL_HOST_PASSWORD = ''

# Google API Key
GOOGLE_API_KEY = ''
SPREADSHEET_ID = ''
JSON_KEY = {}
# Logging Config
LOGGING = {
    'version': 1,
    # Version of logging
    'disable_existing_loggers': False,
 
    'formatters': {
        'default': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
            'datefmt':'%d/%b/%Y %H:%M:%S %z'
        },
    },
    'handlers': {
        'request_log_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': './Log/request_log/'+ datetime.now(timezone(timedelta(hours=+7))).strftime('%d_%m_%Y.log'),
            'formatter':'default'
        },
        'workshop_log_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': './Log/workshop_log/'+ datetime.now(timezone(timedelta(hours=+7))).strftime('%d_%m_%Y.log'),
            'formatter':'default'
        },
        'backends_file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': './Log/admin_log/'+ datetime.now(timezone(timedelta(hours=+7))).strftime('%d_%m_%Y.log'),
            'formatter':'default',
        },
 
        'console': {
            'class': 'logging.StreamHandler',
            'formatter':'default'
        },
    },
    'loggers': {
        'request_log': {
            'handlers': ['request_log_file','console'],
            'level': 'INFO',
            'propagate': False,           
        },
        'workshop_log': {
            'handlers': ['workshop_log_file','console'],
            'level': 'INFO',
            'propagate': False,           
        },
        'django.db.backends': {
            'level': 'DEBUG',
            'handlers': ['backends_file']
        }
    }
}

try:
    from .local_settings import *
except ImportError:
    print('No local file')
