# Generated by Django 4.0.4 on 2022-05-23 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 23, 4, 16, 37, 328156)),
        ),
    ]
