# Generated by Django 4.0.4 on 2022-06-02 06:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_participant_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 2, 6, 9, 54, 38724, tzinfo=utc)),
        ),
    ]
