# Generated by Django 4.0.4 on 2022-06-10 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_participant_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
