# Generated by Django 4.0.4 on 2022-06-23 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_remove_participant_join_date_participant_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
