# Generated by Django 4.0.4 on 2022-07-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_alter_participant_options_alter_participant_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshop',
            options={'verbose_name': 'Workshop', 'verbose_name_plural': 'Workshop'},
        ),
        migrations.AddField(
            model_name='participant',
            name='qrcode',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
