# Generated by Django 4.0.4 on 2022-09-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_alter_workshop_options_participant_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='Workshop đặc biệt'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='ticket_template',
            field=models.ImageField(default='ticket_template.png', upload_to='ticket/ticket_template', verbose_name='Ảnh vé'),
        ),
    ]
