# Generated by Django 4.0.4 on 2022-09-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_workshop_is_special_workshop_ticket_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='ticket_template',
            field=models.ImageField(upload_to='ticket/ticket_template', verbose_name='Ảnh vé'),
        ),
    ]
