# Generated by Django 4.0.4 on 2022-09-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_alter_workshop_ticket_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='address',
            field=models.CharField(default='', max_length=254, verbose_name='Địa chỉ'),
        ),
    ]
