# Generated by Django 4.0.4 on 2022-10-16 11:07

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_alter_workshop_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='ticket_template',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[720, 1280], upload_to='ticket/ticket_template', verbose_name='Ảnh vé'),
        ),
    ]
