# Generated by Django 4.0.4 on 2022-10-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0016_alter_workshop_ticket_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='intro_link',
            field=models.URLField(blank=True, verbose_name='Link giới thiệu'),
        ),
    ]
